import type { ThuongHieu } from "@/src/types/brand.types";

// ─── Brand mock data ──────────────────────────────────────────────────────────
// 8 brands matching the brands used in MOCK_PRODUCTS.

export const MOCK_BRANDS: ThuongHieu[] = [
  {
    id: "brand-001",
    name: "ASUS",
    slug: "asus",
    description: "Tập đoàn công nghệ ASUS - nhà sản xuất GPU, bo mạch chủ, màn hình hàng đầu",
    websiteUrl: "https://www.asus.com",
    active: true,
    productCount: 3,
    createdAt: "2025-10-01T07:00:00Z",
    updatedAt: "2026-03-01T08:00:00Z",
  },
  {
    id: "brand-002",
    name: "Intel",
    slug: "intel",
    description: "Nhà sản xuất CPU Intel Core và Xeon",
    websiteUrl: "https://www.intel.com",
    active: true,
    productCount: 1,
    createdAt: "2025-10-01T07:00:00Z",
    updatedAt: "2026-03-01T08:00:00Z",
  },
  {
    id: "brand-003",
    name: "Samsung",
    slug: "samsung",
    description: "Tập đoàn Samsung - nhà sản xuất SSD, RAM, màn hình",
    websiteUrl: "https://www.samsung.com",
    active: true,
    productCount: 1,
    createdAt: "2025-10-01T07:00:00Z",
    updatedAt: "2026-03-01T08:00:00Z",
  },
  {
    id: "brand-004",
    name: "G.Skill",
    slug: "g-skill",
    description: "Thương hiệu RAM và SSD hiệu năng cao G.Skill",
    websiteUrl: "https://www.gskill.com",
    active: true,
    productCount: 1,
    createdAt: "2025-10-01T07:00:00Z",
    updatedAt: "2026-03-01T08:00:00Z",
  },
  {
    id: "brand-005",
    name: "Noctua",
    slug: "noctua",
    description: "Thương hiệu tản nhiệt cao cấp Noctua từ Áo",
    websiteUrl: "https://www.noctua.at",
    active: true,
    productCount: 1,
    createdAt: "2025-10-01T07:00:00Z",
    updatedAt: "2026-03-01T08:00:00Z",
  },
  {
    id: "brand-006",
    name: "Lian Li",
    slug: "lian-li",
    description: "Nhà sản xuất vỏ case và tản nhiệt nước Lian Li từ Đài Loan",
    websiteUrl: "https://www.lian-li.com",
    active: true,
    productCount: 1,
    createdAt: "2025-10-01T07:00:00Z",
    updatedAt: "2026-03-01T08:00:00Z",
  },
  {
    id: "brand-007",
    name: "AMD",
    slug: "amd",
    description: "Nhà sản xuất CPU Ryzen và GPU Radeon",
    websiteUrl: "https://www.amd.com",
    active: true,
    productCount: 0,
    createdAt: "2025-10-01T07:00:00Z",
    updatedAt: "2026-03-01T08:00:00Z",
  },
  {
    id: "brand-008",
    name: "Corsair",
    slug: "corsair",
    description: "Thương hiệu RAM, SSD, nguồn, case Corsair",
    websiteUrl: "https://www.corsair.com",
    active: false,
    productCount: 0,
    createdAt: "2025-10-01T07:00:00Z",
    updatedAt: "2026-01-10T08:00:00Z",
  },
];
